# docker-compose.yml

version: '3.9'

services:
  db:
    image: postgres:15
    container_name: school-ips-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_ips
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    container_name: school-ips-app
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/school_ips
    command: >
      sh -c "poetry run streamlit run app/main.py --server.port=8501 --server.address=0.0.0.0"

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.13
    container_name: school-ips-dbt
    depends_on:
      - db
    environment:
      DBT_PROFILES_DIR: /app/dbt_school_ips
    volumes:
      - ./:/app
    working_dir: /app/dbt_school_ips
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  pg_data:
