name: "school_ips"
version: "1.0"
profile: "school_ips"

packages-install-path: dbt_packages
clean-targets:
  - "dbt_packages"
  - "target"

models:
  school_ips:
    +materialized: view
    staging:
      +schema: staging
